---

- name: Uploading custom version of BASHRC file for root user
  template:
    src: "{{ item }}"
    dest: /root/.bashrc
    owner: root
    group: root
    mode: 0644
    backup: yes
  with_first_found:
    - "inventory/host_files/{{ inventory_hostname }}/honzamach.commonenv/bashrc.j2"
    - "inventory/group_files/servers-{{ msms_server_type }}/honzamach.commonenv/bashrc.{{ ansible_lsb['codename'] }}.j2"
    - "inventory/group_files/servers-{{ msms_server_type }}/honzamach.commonenv/bashrc.j2"
    - "inventory/group_files/servers/honzamach.commonenv/bashrc.{{ ansible_lsb['codename'] }}.j2"
    - "inventory/group_files/servers/honzamach.commonenv/bashrc.j2"
    - "bashrc.{{ ansible_lsb['codename'] }}.j2"
    - "bashrc.j2"

- name: Uploading custom version of VIMRC file for root user
  template:
    src: "{{ item }}"
    dest: /etc/vim/vimrc
    owner: root
    group: root
    mode: 0644
    backup: yes
  with_first_found:
    - "inventory/host_files/{{ inventory_hostname }}/honzamach.commonenv/vimrc.j2"
    - "inventory/group_files/servers-{{ msms_server_type }}/honzamach.commonenv/vimrc.{{ ansible_lsb['codename'] }}.j2"
    - "inventory/group_files/servers-{{ msms_server_type }}/honzamach.commonenv/vimrc.j2"
    - "inventory/group_files/servers/honzamach.commonenv/vimrc.{{ ansible_lsb['codename'] }}.j2"
    - "inventory/group_files/servers/honzamach.commonenv/vimrc.j2"
    - "vimrc.{{ ansible_lsb['codename'] }}.j2"
    - "vimrc.j2"

- name: Uploading system banner for root user
  template:
    src: "{{ item }}"
    dest: /root/.system-banner
    owner: root
    group: root
    mode: 0755
    backup: yes
  with_first_found:
    - "inventory/host_files/{{ inventory_hostname }}/honzamach.commonenv/system-banner.j2"
    - "inventory/group_files/servers-{{ msms_server_type }}/honzamach.commonenv/system-banner.{{ ansible_lsb['codename'] }}.j2"
    - "inventory/group_files/servers-{{ msms_server_type }}/honzamach.commonenv/system-banner.j2"
    - "inventory/group_files/servers/honzamach.commonenv/system-banner.{{ ansible_lsb['codename'] }}.j2"
    - "inventory/group_files/servers/honzamach.commonenv/system-banner.j2"
    - "system-banner.{{ ansible_lsb['codename'] }}.j2"
    - "system-banner.j2"
