---

- name: Uploading custom version of BASHRC file for root user
  template:
    src: "{{ item }}"
    dest: /root/.bashrc
    owner: root
    group: root
    mode: 0644
    backup: yes
  with_first_found:
    - "host_files/{{ inventory_hostname }}/bashrc.j2"
    - "group_files/servers-production/bashrc.{{ ansible_lsb['codename'] }}.j2"
    - "group_files/servers-production/bashrc.j2"
    - "group_files/servers-development/bashrc.{{ ansible_lsb['codename'] }}.j2"
    - "group_files/servers-development/bashrc.j2"
    - "group_files/servers-demo/bashrc.{{ ansible_lsb['codename'] }}.j2"
    - "group_files/servers-demo/bashrc.j2"
    - "group_files/servers/bashrc.{{ ansible_lsb['codename'] }}.j2"
    - "group_files/servers/bashrc.j2"
    - "bashrc.{{ ansible_lsb['codename'] }}.j2"
    - "bashrc.j2"

- name: Uploading custom version of VIMRC file for root user
  template:
    src: "{{ item }}"
    dest: /etc/vim/vimrc
    owner: root
    group: root
    mode: 0644
    backup: yes
  with_first_found:
    - "host_files/{{ inventory_hostname }}/vimrc.j2"
    - "group_files/servers-production/vimrc.{{ ansible_lsb['codename'] }}.j2"
    - "group_files/servers-production/vimrc.j2"
    - "group_files/servers-development/vimrc.{{ ansible_lsb['codename'] }}.j2"
    - "group_files/servers-development/vimrc.j2"
    - "group_files/servers-demo/vimrc.{{ ansible_lsb['codename'] }}.j2"
    - "group_files/servers-demo/vimrc.j2"
    - "group_files/servers/vimrc.{{ ansible_lsb['codename'] }}.j2"
    - "group_files/servers/vimrc.j2"
    - "vimrc.{{ ansible_lsb['codename'] }}.j2"
    - "vimrc.j2"

- name: Uploading system banner for root user
  template:
    src: "{{ item }}"
    dest: /root/.system-banner
    owner: root
    group: root
    mode: 0755
    backup: yes
  with_first_found:
    - "host_files/{{ inventory_hostname }}/system-banner.j2"
    - "group_files/servers-production/system-banner.{{ ansible_lsb['codename'] }}.j2"
    - "group_files/servers-production/system-banner.j2"
    - "group_files/servers-development/system-banner.{{ ansible_lsb['codename'] }}.j2"
    - "group_files/servers-development/system-banner.j2"
    - "group_files/servers-demo/system-banner.{{ ansible_lsb['codename'] }}.j2"
    - "group_files/servers-demo/system-banner.j2"
    - "group_files/servers/system-banner.{{ ansible_lsb['codename'] }}.j2"
    - "group_files/servers/system-banner.j2"
    - "system-banner.{{ ansible_lsb['codename'] }}.j2"
    - "system-banner.j2"
