---

- name: LSB distribution codename
  debug:
    msg: "System '{{ inventory_hostname }}' is running '{{ ansible_lsb['codename'] }}' distibution"
  tags:
    - debug

- name: Uploading custom version of sources.list
  template:
    src: "{{ item }}"
    dest: /etc/apt/sources.list
    owner: root
    group: root
    mode: 0644
    backup: yes
  with_first_found:
    - "inventory/host_files/{{ inventory_hostname }}/honzamach.commonenv/sources.list.j2"
    - "inventory/group_files/servers_{{ msms_server_type }}/honzamach.commonenv/sources.list.{{ ansible_lsb['codename'] }}.j2"
    - "inventory/group_files/servers/honzamach.commonenv/sources.list.{{ ansible_lsb['codename'] }}.j2"
    - "sources.list.{{ ansible_lsb['codename'] }}.j2"
  notify:
    - Refresh APT cache

- meta: flush_handlers

- name: Forcing APT cache update
  apt: update_cache=yes
  tags:
    - update-cache
  when: hm_commonenv__pkgcache_force_update

- name: Removing any unnecessary system packages
  apt:
    name: "{{ hm_commonenv__remove_packages[ansible_os_family|lower]['apt'] }}"
    state: absent

- name: Installing essential system packages
  apt:
    name: "{{ hm_commonenv__install_packages[ansible_os_family|lower]['apt'] }}"
    state: present

- name: Creating directories
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  loop:
    - /opt/msms/lib/

- name: Installing MSMS library files
  copy:
    src: "{{ item }}"
    dest: "/opt/msms/lib/{{ item }}"
    owner: root
    group: root
    mode: 0644
  loop:
    - libmsms.sh
